CREATE TABLE ALUNO(
Nm_Nome VARCHAR (50),
Nm_Pai VARCHAR(50),
Nm_Mae VARCHAR (50),
Dt_Nascimento DATE,
id_Sexo CHAR(1),
Nr_Rgm NUMBER(8),

CONSTRAINT PK_ALUNO PRIMARY KEY (Nr_Rgm)
);

CREATE TABLE MATRICULA (
Nr_Rgm NUMBER (8),
Cd_Classe NUMBER(8),
Dt_Matricula DATE,

CONSTRAINT FK_MATRICULA_Nr_Rgm FOREIGN KEY (Nr_Rgm) REFERENCES ALUNO (Nr_Rgm),
CONSTRAINT FK_MATRICULA_Cd_Classe FOREIGN KEY (Cd_Classe) REFERENCES CLASSE (Cd_classe)

);

CREATE TABLE CLASSE(
Cd_Classe NUMBER (8),
Nr_AnoLetivo NUMBER (4),
Nr_Serie NUMBER (2),
Sg_Turma VARCHAR2(2),
Cd_Escola NUMBER (6),
Cd_Grau NUMBER (2),
Cd_Periodo NUMBER (2),

CONSTRAINT PK_CLASSE PRIMARY KEY (Cd_Classe)
);

